### ISSUE TITLE
Playback position doesn't immediately reset on track change

### ISSUE THREAD

**Issue by Chaphasilor** [Pato05/just_audio_media_kit#10]
It seems like the track change event doesn't include the the new playback position (of 00:00), so after changing tracks the end position (total duration) of the previous track is briefly shown as the current position for the new track, before it resets.

Here's a clip showing the issue:

https://github.com/Pato05/just_audio_media_kit/assets/18015147/24e8e761-cea3-4e22-94e6-6c03d1c97235

Can you reproduce this, or are we maybe doing something wrong in our app? I haven't taken a deep dive into the issue yet...

**Comment by Pato05** [comment]
That is known as well, however I haven't given it too much attention as it's a minor bug.

The solution is most likely setting `_bufferPosition = _position = Duration.zero;` in [mediakit_player.dart:67](https://github.com/Pato05/just_audio_media_kit/blob/main/lib/mediakit_player.dart#L67).

However as I said in the other issue, I'm currently busy and cannot test this.
