### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0 

### ISSUE THREAD

**Issue by encrystudio** [Pato05/just_audio_media_kit#16]
The above Error appears when I try to play from an URL. More precise: player.load() (player is an instance of the just_audio AudioPlayer). It comes basically from MediaKitPlayer, line 39, 36 called by Line 60, 13. Is it a known issue or am I doing something wrong?

**Comment by lvyueyang** [comment]
The author doesn't seem to have time to fix this bug, you can refer to my PR and make changes yourself.

https://github.com/Pato05/just_audio_media_kit/pull/17
