### ISSUE TITLE
Seeking before playback start not working consistently

### ISSUE THREAD

**Issue by Chaphasilor** [Pato05/just_audio_media_kit#6]
We have a feature where the last queue is restored when restarting our app. If the user already listened to X seconds of the current track, the player state will be restored to that position by first loading the queue (a `ConcatenatingAudioSource`), and then calling `player.seek()` to set the player to the correct position.

However, the position will reset to 0 before playback starts. I've had it work before when using debug builds (release build didn't work), but cannot reproduce that any longer. Currently it's resetting to 0 every time.  
Similar behavior can also be observed with the just_audio_media_kit_example project, where seeking before playback starts will also be briefly reflected in the UI, but then playback will start at 0. This can be tested with the following modification:

```diff
try {
  // Preloading audio is not currently supported on Linux.
  await _player.setAudioSource(_playlist,
      preload: kIsWeb || defaultTargetPlatform != TargetPlatform.linux);
+ await _player.stop();
+ await _player.seek(const Duration(seconds: 45));
} catch (e) {
```

**Comment by Chaphasilor** [comment]
Interesting. I'll try this out tomorrow. Thanks for taking a look.  
Hopefully the fix will be released soon, but the workaround would definitely be nice to have if it works. I'll report back!

**Comment by Pato05** [comment]
@Chaphasilor Any news?

**Comment by Chaphasilor** [comment]
Haven't had time to look at it yet, busy with exams. But we're making progress with desktop support on all fronts, so I will definitely check this out in the coming days!

**Comment by Pato05** [comment]
`just_audio_media_kit` v2.0.2 has been published which includes the fix (albeit _temporary_)

**Comment by Chaphasilor** [comment]
Okay, technically that was "in the coming days", but I'm still sorry it took me so long to take a look. Everything works fine with the update! Thanks a lot :)  
Onto the remaining issues... ^^
